name: My work
favicon: null
layout_spectrum: 0.5372610888443887
typography_spectrum: 0.3726152554154396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7494573451112956
  lightness: 0.8162373304367065
  saturation: 0.05448705214075744
  rhythmicContrast: 0.6287441113963723
purpose: []
